### ISSUE TITLE
Allow setting media type

### ISSUE THREAD

**Issue by pofider** [jsreport/jsreport-chrome-pdf#10]
Using bootstrap to print pdf is usually pain because it applies some custom styles for `print` media. This usually unwanted.

Puppeteer supports [changing media type](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#pageemulatemediamediatype) when printing pdf.

```js
page.emulateMedia('screen')
```

The default `print` makes sense. However we could introduce new option `chrome.mediaType` and let user change to normal `screen`.

**Comment by elessariel** [comment]
Any estimates on this when you might be able to get to it ?

**Comment by pofider** [comment]
released in jsreport-chrome-pdf@1.1.0

**Comment by pofider** [comment]
@elessariel Please let me know if this fixed your problems.

**Comment by elessariel** [comment]
works like a charm, thx a lot :-)
