### ISSUE TITLE
Images not rendering in header/footer

### ISSUE THREAD

**Issue by kfrederix** [jsreport/jsreport-chrome-pdf#12]
Hey guys,

Trying to render some reports with header and footer containing images, but I can't seem to get it working.
The images show up as "broken"... e.g.
![broken_image](https://user-images.githubusercontent.com/3974918/41529833-aac719e2-72ee-11e8-8d9d-5978f832743c.png)

Same images are working perfectly in main template.
Any idea's what I could be doing wrong?

Sidenote 1: I'm using js-report core directly in a node app. Images are referenced using absolute http urls (not using "assets"...)
Sidenote 2: when switching to phantom-pdf recipe, all images are showing correctly in header and footer.

**Comment by pofider** [comment]
Unfortunately http referenced images in chrome default header/footer are not supported.
https://github.com/GoogleChrome/puppeteer/issues/2443

You need to use base64/assets or pdf utils.

**Comment by kfrederix** [comment]
Oh I see, didn't know that...
Thank you for the quick response!!
