### ISSUE TITLE
Attempting to run on heroku

### ISSUE THREAD

**Issue by eamonpenland** [jsreport/jsreport-chrome-pdf#14]
No problem running this recipe locally, but I'm trying to run this recipe on heroku and receiving this issue.

<img width="714" alt="screen shot 2018-07-10 at 2 59 23 pm" src="https://user-images.githubusercontent.com/3287982/42531450-fc8f5c20-8451-11e8-9fd7-6c765de6d36f.png">

Any ideas?

**Comment by pofider** [comment]
The puppeteer/chrome doesn't run by default in limited environment.
https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md

The recommendation here is to pass the arg `--no-sandbox` using config
```js
"extensions": {  
  "chrome-pdf": {  
    "launchOptions": {  
      "args": ["--no-sandbox"]  
    } 
  }
}
```

Or run our official docker image on heroku
[jsreport/jsreport](https://hub.docker.com/r/jsreport/jsreport/)

I haven't try to run jsreport on heroku yet, but hope this helps.

**Comment by eamonpenland** [comment]
That worked! Thanks!
