### ISSUE TITLE
Content is cut at the right of the page

### ISSUE THREAD

**Issue by olivierr91** [jsreport/jsreport-chrome-pdf#16]
I am trying to switch from PhantomPDF to Chrome in .NET and having some issues. Content is cut at the right of the page. In the Chrome rendering below, you can see that the table has some missing pixels.

Here the PhantomPDF rendering result:

[commandes_dachat_avec_items_2018_07_18_10_10_08.pdf](https://github.com/jsreport/jsreport-chrome-pdf/files/2206110/commandes_dachat_avec_items_2018_07_18_10_10_08.pdf)

Here the Chrome rendering result with the same code:

[commandes_dachat_avec_items_2018_07_18_09_43_03.pdf](https://github.com/jsreport/jsreport-chrome-pdf/files/2206111/commandes_dachat_avec_items_2018_07_18_09_43_03.pdf)

**Comment by pofider** [comment]
The output form phantomjs and chrome is not expected to be 1:1
You probably need to adapt styles to make the table smaller.

**Comment by olivierr91** [comment]
Things is body and table have 100% width, content should not go outside the bounds of the content rendering area. I could hard-code a fixed width or apply some corrective padding, but it seems like a hacky workaround for a bug in the rendering stack. I do not have enough understanding of the jsreport stack to know if it's a bug in jsreport itself, Pupeteer or other framework behind it?

**Comment by pofider** [comment]
I see. Based on the testing I see chrome is making table content smaller and smaller if the width is 100% but the actual width is bigger. However at some point it stops and makes a cut.

The phantomjs is doing the same. At some point it also makes a cut. The point when it decides to make the cut comes just a bit later after there is more content than in chrome.

The html-pdf conversion is not part of jsreport. It is task for chrome or for phantomjs.

I am closing this as there is nothing we can do with it from our side.
