### ISSUE TITLE
ENOENT: no such file or directory: \Temp\jsreport\autocleanup\

### ISSUE THREAD

**Issue by gustavomassa** [jsreport/jsreport-chrome-pdf#18]
Hello,

After rendering some templates, this error starts to happen, then I'm unable to render reports until I restart the jsreport service.

`Error: ENOENT: no such file or directory, open 'C:\Users\GUSTAV~1.MAS\AppData\Local\Temp\jsreport\autocleanup\8054d58c-0f12-4e9d-b40d-7ef56df600f1-chrome-pdf.html'`

**Comment by pofider** [comment]
Does this happen on a particular template or also on a "hello world" one?
Are you able to consistently replicate this?

**Comment by gustavomassa** [comment]
> Does this happen on a particular template or also on a "hello world" one?
I'm using always the same template when this error occurs.

> Are you able to consistently replicate this?
Yes, after rendering 5-10.. times the template, the error starts to happen.

![image](https://user-images.githubusercontent.com/16235598/44878446-4ac34200-ac7d-11e8-8d12-66deb988ff31.png)

The function responsible for rendering the template:
```
public async renderTemplate(template: string, model: object): Promise<WBA.Webbuffet> {
        const result: Promise<WBA.Webbuffet> = new Promise(async (resolve, reject, onCancel) => {
            try {
                if (!template || !model) return reject(WBA.error(WBA.Status.ERROR_NULL_PARAMETER, 'template/model is NULL'));

                let operation: Promise<any> = undefined;
                onCancel(() => {
                    if (operation) operation.cancel();
                    return;
                });

                const response: jsreportCreator.Response = await this.jsreport.render(<any>{
                    template: { name: template, },
                    data: { model: model }
                });

                //fs.writeFileSync('report.pdf', response.content);

                return resolve(WBA.success(response.content));

            } catch (ex) {
                return reject(WBA.exception(new Error(ex)));
            }
        });
        return result;
    }
```

The error occurs on chrome.js from jsreport-chrome-pdf:
Line: 126
![image](https://user-images.githubusercontent.com/16235598/44880376-a7752b80-ac82-11e8-81a9-0614f756cbbd.png)

When the error occurs the folder "~\AppData\Local\Temp\jsreport" exists, but is empty.
When the render works fine the folder jsreport has two empty folders inside:
![image](https://user-images.githubusercontent.com/16235598/44880718-b1e3f500-ac83-11e8-94f6-a617eac16efc.png)

So the problem is that something at some time is deleting the folder "autocleanup"

**Comment by pofider** [comment]
Thanks. I suspected this.
I think it is something at your workstation that is deleting those folders.
We just delete files inside the autocleanup.
The windows should not do this by default based on the documentation. Maybe you have some software like an antivirus.

If you are not able to find out what is cleaning it up, you can set global config `tempDirectory` to  another location and you should be fine.
https://jsreport.net/learn/configuration
