### ISSUE TITLE
puppeteer/chrome version

### ISSUE THREAD

**Issue by djmurf** [jsreport/jsreport-chrome-pdf#2]
Was curious if there is a reason that the chrome-pdf plugin is current using puppeteer 0.13.0

The version of chrome/chromium that it's installing is crashing on a highchart that I'm rendering, which is rendering fine in current chrome. As a test I upgraded the local puppeteer to ^1.0.0 and the latest version of chrome/chromium it installs does not crash in this scenario.

I can provide details on the actual crash if necessary, just wondering if it's possible at this point to upgrade the internal dependency of puppeteer to the 1.x release. 

Thanks

**Comment by pofider** [comment]
No reason. I will upgrade it.
The future versions will anyway exclude this dependency and let it up to you to use particular one.

**Comment by djmurf** [comment]
Thank you sir! Appreciate the fast response.

**Comment by pofider** [comment]
The jsreport-chrome-pdf@0.3.0 is now released with the latest puppeteer.

**Comment by djmurf** [comment]
Just upgraded -- working like a champ. Thanks again.

**Comment by pofider** [comment]
Thank you for the confirmation.
