### ISSUE TITLE
Break page and repeat background 

### ISSUE THREAD

**Issue by davidbranco** [jsreport/jsreport-chrome-pdf#21]
Hi guys! Awesome work with jsreport.

I'm facing an issue here.
I have a document that are divided like this:

- SOME INFO LIKE CUSTOM HEADER (not standard chrome pdf header)
- SOME INFO LIKE BODY
- SOME INFO LIKE CUSTOM FOOTER (not standard chrome pdf footer)

This document have a background on the entire page. This background have some limitations. So, when some values are about to break the limit of the page, I need to go to a new page, with the same background than the previous page.
But, more than this, on the next page I need to repeat CUSTOM HEADER and CUSTOM FOOTER.

What I did so far:
- Using beforeRender to try implement some template validation
```
function beforeRender(req, res, done) {
    let layout = '{#asset bl_cover.html @encoding=string}'
    req.template.content = layout.replace('$$$bl_data$$$', req.template.content)
    done();
}
```

- Using some html template and only making an injection of a div (_ugly as f*ck, actually_)
```
<body>
    <div class="cover">$$$bl_data$$$</div>
    <div class="no-show {{showOtherPages model.PROCESS.SHOW_SECOND_PAGE}}">
        <div class="break"></div>
    </div>
    <div class="cover no-show {{showOtherPages model.PROCESS.SHOW_SECOND_PAGE}}">$$$bl_data$$$</div>
</body>
```

After all this (just a little context) what I need is create new pages automatically. If data will break my document, I break the page and than set data continuation on new page. And so on.

If you guys need more info, pls tell me. Help me, pls.

**Comment by bjrmatos** [comment]
hmm is it possible that you can publish your case in our playground, save it and then share the link here? i think this can be solved by using [pdf-utils](https://jsreport.net/learn/pdf-utils) headers/footers but it will be much better to see the source of your case to understand under which situations it breaks and what can be the solution.

**Comment by davidbranco** [comment]
Here man: https://playground.jsreport.net/w/davidbranco/EBKlktcW

**Comment by bjrmatos** [comment]
ok, i think you can use [pdf-utils](https://jsreport.net/learn/pdf-utils) to have what you want, pdf-utils can merge pdf output, so you can put the html of cover (the background of your pdf) in a pdf-utils template, so that content will be merged always where there is new page in your template, so if your template produces two pages, the pdf-utils will merge the cover always for all the pages produced, maybe you can try that since i don't see a limitation in that approach, or maybe you find one, but i'm sure you should try pdf-utils for this case and see how far you get

**Comment by davidbranco** [comment]
@bjrmatos I did it using pdf-utils and using a for clause to iterate whatever amount of pages. Thanks for your help.
```
{{#each model.PROCESS}}
<div style='page-break-before: always;'></div>
{{/each}}
```
