### ISSUE TITLE
PDF File size increases dramatically when HTML contains bold text

### ISSUE THREAD

**Issue by shai-glat** [jsreport/jsreport-chrome-pdf#22]
Hello,
I am generating a PDF from an html template that i build. As part of the template i mark a few words as bold in the middle of a sentence. However, when i do this the output PDF is massively larger. Here's some examples:
1. First file: surrounded 8 words with `<b>` or `<span style="text-weight: bold;">`. Resulting file size went up from 27k to 72k
2. Second file: surrounded 12 words with same tags. Result file size went up to 125k from 31k
3. I have replaced the tags with `<u>` tag and the file did not increase (27k/31k)

This happens on my ASP.Net Core service. I use jsreport.AspNetCore (2.0.1) with jsreport.Binary (2.4.0), jsreport.Local (2.0.1) and jsreport.Client (3.0.1).
Any idea what can cause this scenario?

**Comment by pofider** [comment]
I apologize for late response.

Unfortunately, this is something we don't have any influence on.
You would need to fill a ticket to the chromium.

Maybe they need to embed additional fonts to the pdf when there is a bold text. However, that is just a guess.

**Comment by shai-glat** [comment]
Thanks for the response, as late as it may be.

Can you please explain to me how the responsibility is divided? i was under the impression that the PDF rendering is done by jsreport itself and not chromium.
Do you understand what is causing the extra PDF size? if so, can you explain to me please?

**Comment by pofider** [comment]
> Can you please explain to me how the responsibility is divided? i was under the impression that the PDF 

No. jsreport prepares source html and then sends it to the chromium which converts it into the pdf.


I don't know what is the cause of the increased size. As I mentioned it could be the additional font which may be added for bold. You can try to inspect the pdf using a tool like this and see what is inside

https://github.com/itext/rups/

**Comment by shai-glat** [comment]
hello,
I have now switched from local jsreport binary to server connection. I have ran against jsreport 2.3.0 docker from hub and the bug does not reproduce. What chromium is used by jsreport.Binary and jsreport.Binary.Linux?
Please note that while my bug is resolved i'd love to help if anything else is needed :)

**Comment by pofider** [comment]
we have to make this a bit more consistent...

docker images are using chromium `64.0.3282.168-r0` as you can see here
https://github.com/jsreport/jsreport/blob/master/docker/default/Dockerfile#L9

to find out what binary use you can look here
https://github.com/jsreport/jsreport/blob/2.3.0/package.json#L72
https://github.com/GoogleChrome/puppeteer/releases/tag/v1.11.0
so for v 2.3.0 it is 72.0.3618.0

I've submitted a task to our backlog to make sure these versions are consistent.
I apologize for this friction.
https://github.com/jsreport/jsreport/issues/554
