### ISSUE TITLE
compatibility with puppeteer 2.0

### ISSUE THREAD

**Issue by abenhamdine** [jsreport/jsreport-chrome-pdf#24]
I saw that in package.json puppeteer is listed as peerDependency with range 1.x.x  

but puppeteer 2.0 has been released in october (https://github.com/puppeteer/puppeteer/releases) and the only breaking change seems to be end of support for node 6.x
Thus do you think/know if this module could work reliably with puppeteer 2.x ? Do you plan to support it and change peerDependency range ?  

thx by advance

**Comment by pofider** [comment]
I updated the range.
We will ship this to npm package soon as well.
