### ISSUE TITLE
emulateMedia option no longer supported in puppeteer

### ISSUE THREAD

**Issue by charlietilt** [jsreport/jsreport-chrome-pdf#26]
It appears that the latest version of puppeteer 5.3.1 does not support the `emulateMedia` option.
It looks as though they have renamed the method to `emulateMediaType`

This block of code will cause the pdf creation to fail if `chrome.mediaType` is set to `screen` or `print`
```
    if (optionsToUse.mediaType) {
      if (optionsToUse.mediaType !== 'screen' && optionsToUse.mediaType !== 'print') {
        throw reporter.createError(`chrome.mediaType must be equal to 'screen' or 'print'`, { weak: true })
      }

      await page.emulateMedia(optionsToUse.mediaType)
    }
```

**Comment by abenhamdine** [comment]
Indeed, this deprecated method has been removed in pupeeter 5.0.0, see breaking changes. https://github.com/puppeteer/puppeteer/releases/tag/v5.0.0

I will send a PR to check for old/new name

**Comment by pofider** [comment]
Thank you, PR merged
