### ISSUE TITLE
Add the preview to NuGet as a pre-release

### ISSUE THREAD

**Issue by olivierr91** [jsreport/jsreport-chrome-pdf#7]
I would like to use the chrome-pdf recipe in my .NET Core project before final release, is this possible?

**Comment by fabich** [comment]
@pofider is there a NuGet version in development?

**Comment by pofider** [comment]
The .net nugets are now pre-released with jsreport v2 and chrome.
https://github.com/jsreport/jsreport-dotnet/issues/21
