### ISSUE TITLE
Re-use Chrome instances for performance

### ISSUE THREAD

**Issue by deadwards90** [jsreport/jsreport-chrome-pdf#8]
I noticed that as part of the recipe, Chrome is launched and then closed each time a PDF is generated.

Would it not be better to try and keep Chrome alive once it has first been launched. Or, if you wanted to be really fancy, have a swarm of Chromes to connect to?

**Comment by pofider** [comment]
Yes, this is on our [roadmap](https://github.com/jsreport/jsreport#roadmap). We will get to it soon. 
And yes, the plan is to have swarm of chrome nodes the same as we have with phantomjs in v1.

**Comment by deadwards90** [comment]
I missed that!

Do you have any timeline on this, out of interest? I know these things are hard to gauge. We've got a project happening basically now and it's basically a blocker to us using it as the performance just isn't there for our needs, but we'd still like to use Chrome as the PDF engine.

**Comment by pofider** [comment]
Hm. Some weeks. Hard to say. 
How about you fork the recipe for your internal purpose for now and just don't close chrome. This should be couple of lines changes.

**Comment by deadwards90** [comment]
We'll look into it 👍
