### ISSUE TITLE
Issue with landscape-mode

### ISSUE THREAD

**Issue by elessariel** [jsreport/jsreport-chrome-pdf#9]
Hello,
I'm not sure if this is jsreport-chrome-pdf related but I'm having issues with the landscape mode. Everything else if working finde, however the landscape option doesn't seem to do anything.

my script:
```js
module.exports = function (callback, html, header, footer, settings, js) {
	var jsreport = require('jsreport-core')();	
	jsreport.use(require('jsreport-jsrender')())
	jsreport.use(require('jsreport-chrome-pdf')())

	//210 mm × 297 mm 
	jsreport.init().then(() => {
	return jsreport.render({
		template: {
			content: html,
			engine: 'jsrender',
			helpers: js,
			recipe: 'chrome-pdf',
			chrome: {
			  landscape: true,
			  displayHeaderFooter: true,
			  format: 'A4',
			  headerTemplate: header,
			  footerTemplate: footer,
			  marginTop: '130px',
			  marginBottom: '110px',
			  marginLeft: '105px',
			  marginRight: '105px'
			 }			
		},
		data: null
	}).then((resp) => {
		callback(null, resp.content.toJSON().data);
 	});
	}).catch((e) => {
		callback(e, null);
	});
}
```

I also tried the scale option once with scale: 1 (basically the default) but that resulted in a 
```
Protocol error (Page.printToPDF): Target closed.
Error: Protocol error (Page.printToPDF): Target closed.
```

really hope you guys might have an idea.

Edit: thought I should mention I'm on these versions:
"jsreport-chrome-pdf": "1.0.2",
    "jsreport-core": "2.0.1",
    "jsreport-jsrender": "2.0.0",

**Comment by Avenel** [comment]
Hello,

i am glad that i am not the only one with this issue. Is there any explanation for this?

**Comment by pofider** [comment]
Can you try out exactly this code and upload the pdf result? It works for me and the output is in landscape.

```js
var jsreport = require('jsreport-core')()
jsreport.use(require('jsreport-jsrender')())
jsreport.use(require('jsreport-chrome-pdf')())

jsreport.init().then(() => {
  jsreport.render({
    template: {
      content: 'Hello world',
      engine: 'jsrender',
      recipe: 'chrome-pdf',
      chrome: {
        landscape: true,
        displayHeaderFooter: true,
        format: 'A4',
        headerTemplate: 'header',
        footerTemplate: 'footer',
        marginTop: '130px',
        marginBottom: '110px',
        marginLeft: '105px',
        marginRight: '105px'
      }
    }
  }).then((res) => {
    require('fs').writeFileSync('out.pdf', res.content)
  })
})
```

**Comment by elessariel** [comment]
your code works @pofider and so does mine by now, it seems to be content related because as soon as I put in the html in the content property it switches back to portrait-mode. I'll do some experiments to see if it's length related or something.

edit: Okay I now know the cause: as soon as I include Bootstrap 4.1.x 's CSS landscape-mode goes bye bye. No idea why yet.

**Comment by pofider** [comment]
> edit: Okay I now know the cause: as soon as I include Bootstrap 4.1.x 's CSS landscape-mode goes bye bye. No idea why yet.

My guess would be that bootstrap includes some print styles as
```css
@media print{@page {size: landscape}}
```
You can try to override those. Or evaluate if you need bootstrap, it is not the best fit for fixed sized pdf.

**Comment by elessariel** [comment]
that was exactly it. It seems like  the @page size setting overrides any chrome-pdf setting.
I can override it in some cases, in some others I have no control over the template, so I wonder why css-settings like that overrule the "force"-settings of the config or if there is anything one can do about it ?

**Comment by pofider** [comment]
I don't see such option in the [puppeteer chrome driver docs](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#pagepdfoptions).

However I see we could instruct printing to not use the media type "print". This would prevent bootstrap from adding custom print styles. This could be a new option.

**Comment by elessariel** [comment]
that would indeed be nice, or expose the media-type so once could willingly decide to use the "screen"-type.

**Comment by pofider** [comment]
Closing this issue and creating instead new one for setting media type.

https://github.com/jsreport/jsreport-chrome-pdf/issues/10
